DROP TABLE IF EXISTS application_results;
DROP TABLE IF EXISTS credit_scores;
DROP TABLE IF EXISTS applicants CASCADE;



CREATE TABLE applicants
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    surname VARCHAR NOT NULL,
    national_no VARCHAR(11) NOT NULL UNIQUE ,
    monthly_income INT NOT NULL,
    phone VARCHAR NOT NULL
);

CREATE TABLE credit_scores
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_no VARCHAR(11) NOT NULL,
    credit_score INT DEFAULT 0
    --FOREIGN KEY(national_no) REFERENCES applicants(national_no)
);

CREATE TABLE application_results
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_no VARCHAR(11) ,
    application_result VARCHAR ,
    credit_limit INT DEFAULT 0
    --FOREIGN KEY(national_no) REFERENCES applicants(national_no)
);

INSERT INTO applicants(name, surname, national_no, monthly_income, phone)
VALUES ('ali','kantar','33344455566',2000,'05554443322'),
       ('mehmet','beyran','77744455566',3000,'05444443322');

INSERT INTO credit_scores(national_no, credit_score)
VALUES ('33344455566',500),
       ('77744455566',1000);