DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS "role";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS application_results;
DROP TABLE IF EXISTS credit_scores;
DROP TABLE IF EXISTS applicants CASCADE;




CREATE TABLE applicants
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    surname VARCHAR NOT NULL,
    national_no VARCHAR(11) NOT NULL UNIQUE ,
    monthly_income INT NOT NULL,
    phone VARCHAR NOT NULL
);

CREATE TABLE credit_scores
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_no VARCHAR(11) NOT NULL,
    credit_score INT DEFAULT 0
    --FOREIGN KEY(national_no) REFERENCES applicants(national_no)
);

CREATE TABLE application_results
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_no VARCHAR(11) ,
    application_result VARCHAR ,
    credit_limit INT DEFAULT 0
    --FOREIGN KEY(national_no) REFERENCES applicants(national_no)
);

CREATE TABLE "user"
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(24) UNIQUE NOT NULL,
    email    VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255)  NOT NULL
);

CREATE TABLE "role"
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name varchar(10) UNIQUE NOT NULL
);

CREATE TABLE user_roles
(
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);




INSERT INTO applicants(name, surname, national_no, monthly_income, phone)
VALUES ('ali','kantar','33344455566',2000,'05554443322'),
       ('mehmet','beyran','77744455566',3000,'05444443322');

INSERT INTO credit_scores(national_no, credit_score)
VALUES ('33344455566',500),
       ('77744455566',1000);

INSERT INTO "role" (role_name)
VALUES ('ROLE_ADMIN');
INSERT INTO "role" (role_name)
VALUES ('ROLE_USER');

INSERT INTO "user"(username,email,password)
VALUES ('zeynel','admin@adminonline.com','zeynelacar');
